---
project:
  type: website

format:
  html:
    theme: darkly
  revealjs:
    callout-appearance: simple
    code-copy: true
    footer: "{{< meta title >}} - <https://talks.chooseadb.com>"
    hash-type: number
    history: false
    incremental: true
    link-external-icon: true
    mermaid:
      theme: dark
    menu:
      hideMissingTitles: true
      useTextContentForMissingTitles: false
    slide-number: true
    theme: dark
    transition: fade

website:
  navbar:
    tools:
      - icon: house
        href: https://chooseadb.com
      - icon: github
        href: https://github.com/chooseadb/talks
  title: ""
